### ISSUE TITLE
Cannot find trait `SoAIter` in crate `soa_derive`

### ISSUE THREAD

**Issue by VitalyArtemiev** [lumol-org/soa-derive#47]
After updating soa_derive dependency from 0.10.0 to 0.11.0 any code with #[derive(StructOfArray] fails to compile with the following message:

```
error[E0405]: cannot find trait `SoAIter` in crate `soa_derive`
 --> src\main.rs:3:10
  |
3 | #[derive(StructOfArray)]
  |          ^^^^^^^^^^^^^ not found in `soa_derive`
  |
  = note: this error originates in the derive macro `StructOfArray` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Barebones example project at https://github.com/VitalyArtemiev/testsoa.git

Steps to reproduce:
```
git clone https://github.com/VitalyArtemiev/testsoa.git
cd testsoa
cargo run
```

Tried both with stable and nightly. Sorry if this is a known problem.

**Comment by copying** [comment]
Hi there!
I've validated that this is indeed happening. Using the repository seems to work for me:
```toml
[dependencies]
soa_derive = { git = "https://github.com/lumol-org/soa-derive" }
```

I'm investigating what went wrong. I'll reach back when I know something.

**Comment by copying** [comment]
@Luthaf I believe that publishing `soa_derive_internal` `0.11.1` actually broke `soa_derive` `0.11.0`. The reason being that #41 actually added new things to `soa_derive` and the internals depend on it. I think bumping both versions to `0.12.0` and removing the `0.11.1` from `soa_derive_internal` should work just fine and retroactivelly fix `0.11`. What do you think?

**Comment by Luthaf** [comment]
Thanks for reporting @VitalyArtemiev and thanks for the investigation @copying!

I yanked `soa_derive_internal 0.11.1` & republished both soa-derive and soa-derive at version 0.12.0. 

This fixed the example project with both version (after updating Cargo.lock for 0.11.0). Feel free to re-open if there is another problem!
